app = 'trading-phantich-wyckoff'
primary_region = "nrt"

[build]

[processes]
app = "python -m app.main"

[deploy]
  strategy = "rolling"
  min_machines_running = 2

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"